spring.application.name=RAG_chatbot
server.port=8080
spring.datasource.url=jdbc:h2:mem:testdb
spring.ai.vectorstore.milvus.client.port=19530
# Spring AI config
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.model.chat=ollama
spring.ai.ollama.chat.model=llama3.1


