spring.application.name=RAG_chatbot
server.port=8080

spring.config.import=optional:classpath:env.properties

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}


# Postgres DB config
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# Milvus Vector Database config
spring.ai.vectorstore.milvus.client.port=${VECTOR_DATABASE_PORT}
spring.ai.vectorstore.milvus.client.host=${VECTOR_DATABASE_HOST}
spring.ai.vectorstore.milvus.client.password=${VECTOR_DATABASE_PASSWORD}
spring.ai.vectorstore.milvus.client.username=${VECTOR_DATABASE_USERNAME}

spring.ai.vectorstore.milvus.database-name=${VECTOR_DATABASE_NAME}
spring.ai.vectorstore.milvus.collection-name=${VECTOR_DATABASE_COLLECTION_NAME:chatbot}
spring.ai.vectorstore.milvus.index-type=IVF_FLAT
spring.ai.vectorstore.milvus.metric-type=COSINE

# nomic-embed-text dim embedding vectors
spring.ai.vectorstore.milvus.embedding-dimension=768
spring.ai.vectorstore.milvus.initialize-schema=true
milvus.drop-collection-on-startup=true

# Embedding batching config
spring.ai.embedding.batch.max-tokens=8000
spring.ai.embedding.batch.reserve-percentage=0.1

# Number of documents per vector store insert batch
ingestion.batch-size=1000

# Spring AI config
spring.ai.ollama.base-url=${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.model.chat=ollama
spring.ai.ollama.chat.model=llama3.2:latest

# Ollama embedding model config
spring.ai.ollama.embedding.model=nomic-embed-text

# RAG config
rag.search.default-top-k=15
rag.search.default-similarity-threshold=0.4



logging.level.root=INFO
logging.level.com.rubenzu03.rag_chatbot=INFO
logging.level.com.rubenzu03.rag_chatbot.infrastructure.ragmodules.postretrieve.DocumentPostProcessingModule=DEBUG

# Master key for encryption of Data Encryption Keys (DEKs)
app.security.master-key=${MASTER_KEY:default_master_key_change_me_to_32_bytes_in_production__}

